condition checks before release (closes #12)
projectdiscovery/roundrobin pull request #15
Opened 2022-11-14 20:31 UTC by tarunKoyalwar

## Description

Currently `roundrobin` releases are automatic periodic release  . Hence In cases where there are not updates to library new releases are created . This pull request implements some condition checks to fix that

-  Counts total commits from last release date and and new release is created if it is > 0
-  Handles Some edge cases where it is a first release

closes #12

2022-11-14 20:33 UTC, tarunKoyalwar commented
## Technical Details

### 1. gh cli is used to fetch latest release date

```sh
gh release view  --json publishedAt --jq '.publishedAt' -R github.com/$GITHUB_REPOSITORY
```
### 2. `git log` is used to fetch logs on this branch (main/master) starting from last release 

```sh
git log --pretty=format:%an --since=${{ steps.last_release.outputs.RDATE }}  --oneline | wc -l
```

-  Edge Case where it is a first release of library is handled 

### 3. Expression is used to check if there are any new commits from release date
 
~~~yaml
  if: ${{ steps.available_commits.outputs.COUNT > 0  }}
~~~

Some screenshots from of this in action done on test repo and fork
<img width="1100" alt="commits_available" src="https://user-images.githubusercontent.com/45962551/201760171-3121d750-0940-49e1-acc9-37f487ff8dd1.png">
<img width="1102" alt="first_release" src="https://user-images.githubusercontent.com/45962551/201760183-2f16e5f4-732d-4bcb-aae8-2b04ba7d8b3a.png">
<img width="1121" alt="no_new_commits" src="https://user-images.githubusercontent.com/45962551/201760192-17a8493f-62f4-4128-874d-7d3315f545fb.png">

2022-11-14 20:40 UTC, tarunKoyalwar commented
Due to implementation  changes can be made to periodic release and Release can be manually triggered without updating  conditon checks

2022-11-15 07:29 UTC, ehsandeep reviewed
@tarunKoyalwar this can be simplified as below - 

```yaml
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Commit Count
        id: get_commit
        run: git rev-list  `git rev-list --tags --no-walk --max-count=1`..HEAD --count | xargs -I {} echo COMMIT_COUNT={} >> $GITHUB_OUTPUT

      - name: Create release and tag
        if: ${{ steps.get_commit.outputs.COMMIT_COUNT > 0  }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        if: ${{ steps.get_commit.outputs.COMMIT_COUNT > 0  }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
```

2022-11-15 07:49 UTC, tarunKoyalwar commented
@ehsandeep  , Using tags is also great idea . It passes all tested cases I will update pull request .

2022-11-15 07:53 UTC, Mzack9999 requested changes
marking as changes requested as per @ehsandeep suggestions

2022-11-15 08:07 UTC, ehsandeep approved these changes

2022-11-15 11:53 UTC, Mzack9999 approved these changes
lgtm!

2022-11-15 12:08 UTC, merged